### ISSUE TITLE
DriverQuery: Missing References Break .NET 4.0 Compatibility

### ISSUE THREAD

**Issue by s0lst1c3** [matterpreter/OffensiveCSharp#7]
Project is currently missing references to the following:
- System.Management
- System.ServiceProcess

This breaks compilation when targeting .NET 4.0 as shown in the attached screenshot.

![Screen Shot 2020-03-06 at 9 37 43 AM](https://user-images.githubusercontent.com/5394955/76105634-89346e00-5f92-11ea-8ff7-5617ccdb44c5.png)

**Comment by matterpreter** [comment]
Addressed in 81f393022244e218858f52ecb68760722039b864
